# Generated by Django 6.1.1 on 2026-09-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconfirmation",
            name="purpose",
            field=models.IntegerField(
                choices=[(1, "Signup"), (2, "Forgot Password")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="auth_status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("code_verified", "Code Verified"),
                    ("done", "Done"),
                ],
                default="new",
                max_length=33,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="auth_type",
            field=models.CharField(
                choices=[("via_email", "Via Email"), ("via_phone", "Via Phone")],
                max_length=33,
            ),
        ),
        migrations.AlterField(
            model_name="userconfirmation",
            name="verify_type",
            field=models.CharField(
                choices=[("via_email", "Via Email"), ("via_phone", "Via Phone")],
                max_length=31,
            ),
        ),
    ]
