# Generated by Django 6.1.1 on 2026-09-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="intal_price",
            new_name="rental_price",
        ),
    ]
