# Generated by Django 6.1.1 on 2026-09-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_rename_intal_price_book_rental_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.TextField(),
        ),
    ]
