# Generated by Django 6.1.1 on 2026-09-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.TextField(
                choices=[
                    ("religious", "Religious"),
                    ("story", "Story"),
                    ("fantasy", "Fantasy"),
                    ("science", "Science"),
                    ("history", "History"),
                    ("other", "Other"),
                ]
            ),
        ),
    ]
